name: 'Preview Deployment Pipeline'
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    paths-ignore:
      - README.md

env:
  PROJECT: web-substrate-diff
  NAMESPACE: web-substrate-diff
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  HEAD_BRANCH_NAME: ${{ github.head_ref }}

jobs:
  build:
    timeout-minutes: 10
    name: Lint, build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
      - name: Install dependencies
        run: yarn install
      - name: Run Format
        run: yarn format
      - name: Run linter
        run: yarn linter
      - name: Jest tests
        run: yarn test
      - name: Build
        run: yarn build
